services:
  - type: web
    name: trustguard-sa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1
    plan: free
    envVars:
      - key: ACCESS_TOKEN
        value: EAAYnIXB43fUBRtc9H59RTWbdBI8o3xdZBzX6ZCu17XVEuWuPv50ZBVYlhBtPNEFvcQ3UXdpOrJLYswvP1ojKzWZChMTCAzVcdN3iETTB8XbE6LZCvjWNcbf2tZBNZC0ZBCv1Yu7M5bZC30g0UUe6ldDTQkpU3xBAxzGsynzIXZC2GBZC2dmZA4NWA0v7k5uZAL6Ezq1wfptwYR7gxGcXE5w7fpZCYzHkPc47wwnZBSlYq8pJAIkZBPiTe1ZBFM4bZBtD3JWtJPKEMyXAj9vdq046slR7yo7V9y3gZDZD
      - key: PHONE_NUMBER_ID
        value: "1222834277573081"
      - key: VERIFY_TOKEN
        value: trustguard2026
      - key: HF_TOKEN
        sync: false
